export const UPDATE_ASPECT_RATIO = 'edit/UPDATE_ASPECT_RATIO';
export const UPDATE_SELECTED_FRAME = 'edit/UPDATE_SELECTED_FRAME';
export const UPDATE_CROP = 'edit/UPDATE_CROP';
export const STORE_IMAGE_DIMENSIONS = 'edit/STORE_IMAGE_DIMENSIONS';
