export const UPDATE_SELECTED_FRAME = 'frame/UPDATE_SELECTED_FRAME';
export const UPDATE_SELECTED_COLLECTION = 'frame/UPDATE_SELECTED_COLLECTION';
// export const ADD_FRAME = 'frame/ADD_FRAME';
export const FETCH_FRAMES_START = 'frame/FETCH_FRAMES_START';
export const FETCH_FRAMES_SUCCESS = 'frame/FETCH_FRAMES_SUCCESS';
export const FETCH_FRAMES_FAILURE = 'frame/FETCH_FRAMES_FAILURE';
