const ADD_IMAGES = 'gallery/ADD_IMAGES';
const REMOVE_IMAGES = 'gallery/REMOVE_IMAGES';
const EDIT_IMAGE = 'gallery/EDIT_IMAGE';
const MARK_IMAGE_AS_EDITED = 'gallery/MARK_IMAGE_AS_EDITED';

export {
  ADD_IMAGES,
  REMOVE_IMAGES,
  EDIT_IMAGE,
  MARK_IMAGE_AS_EDITED
};
